- name: Start Docker App
  hosts: localhost
  become: true

  tasks:
    - name: Install Docker Compose
      apt:
        pkg:
          - docker-compose
        state: latest
        update_cache: true

    - name: Pull Git Repository
      git:
        repo: "https://github.com/GraceCeline/Docker.git"
        dest: /home/ubuntu/workshop-project
        version: ansible
        update: yes

    - name: Run Docker Container
      command: docker-compose up --build -d
      args:
        chdir: /home/ubuntu/workshop-project