services:
  django:
    # build: ./Workshop
    container_name: django-rest
    image: gflorensia/workshop-project:django-1.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./config/settings.py:/app/src/settings/settings.py
    environment:
      - DOCKERIZED=1
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    networks:
      - workshop
    depends_on:
      mysql:
        condition: service_healthy
    #restart: always
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10

    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - workshop
  
  angular:
    # build: ./workshop-angular
    container_name: angular
    image: gflorensia/workshop-project:angular-1.0.0
    ports:
     - "4200:80"
    networks:
     - workshop

volumes:
  mysql:
networks:
  workshop:

