version: '3'

services:
  django:
    # build: ./Workshop
    container_name: django-rest
    image: gflorensia/workshop-project:django-1.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./config/settings.py:/app/src/settings/settings.py
    environment:
      DOCKERIZED: "1"
    networks:
      - workshop
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: celine123
      MYSQL_DATABASE: django_db
      MYSQL_USER: grace
      MYSQL_PASSWORD: celine123
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - workshop
  
  angular:
    # build: ./workshop-angular
    container_name: angular
    image: gflorensia/workshop-project:angular-1.0.0
    ports:
     - "4200:80"
    networks:
     - workshop

volumes:
  mysql:
networks:
  workshop:
